### ISSUE TITLE
Create Team Modal Bug

### ISSUE THREAD

**Issue by YazidKurdi** [midday-ai/midday#114]
1. Create team modal accepts an empty string - not sure by design or not.
2. Cancel button does not exit modal
3. Server error when creating new team, to reproduce

- Created two teams, totaling to 3 (the on creation team and 2 teams that had a blank input)
- Deleted 2 blank teams
- Tried to create a new team with the error below

1:{"serverError":{"serverError":"Cannot read properties of null (reading 'id')"}}

**Comment by pontusab** [comment]
Thank you, I will have a look!

**Comment by sreehari2003** [comment]
hey @pontusab  can i work on this, but I was going through the docs and I couldn't find any docs on how to run the app locally .
