### ISSUE TITLE
Tracker day component overflowing the page

### ISSUE THREAD

**Issue by wladpaiva** [midday-ai/midday#126]
<img width="1624" alt="Screenshot 2024-05-28 at 13 33 55" src="https://github.com/midday-ai/midday/assets/1843792/c7cf0be0-9634-4f63-950d-3e5c0ba6ee50">
It doesn’t seem like this is the correct intented behavior

**Comment by pontusab** [comment]
Hey, and thanks for posting this!

Yes that doesn't look great, I will fix this + make the whole dashboard responsive soon!

**Comment by pontusab** [comment]
Viktor is currently making a total new design that makes much more sense regarding UI/UX, i'll post here once we have more!

**Comment by wladpaiva** [comment]
Nice! Thank you guys. Looking forward to start using it and integrate it my workflow

**Comment by pontusab** [comment]
WIP
![Uploading GSx7qmJXoAA52sb.jpg…]()

**Comment by pontusab** [comment]
WIP
![GSx7qmJXoAA52sb](https://github.com/user-attachments/assets/84cbbee1-66eb-4e79-9e30-175d8a48d479)

**Comment by wladpaiva** [comment]
I do not know if I like the project cards over the table. It might be overwhelm to spot big differences in hours spent depending on the number of projects. Maybe keep both? or maybe there's a better place for that?

The thing I like more about the old UI is how easy is to spot what days I haven't filled up yet although I have to admit that not having the weekends and the days being sequentially horizontal is difficult to spot the correct day without doing some mental gymnastics.

Have you guys though on something like this?
![image](https://github.com/user-attachments/assets/c241452c-f590-4c0b-a27e-a69ca4d2f57f)

**Comment by pontusab** [comment]
Great feedback! We will add the table and the cards so you can toggle between them

Regarding the dots vs graph is that it's really hard as you mention to actually know what day is what and do a general overview of this month but we will keep it in the widget in the Overview (startpage) + on the actual project

Let me know what you think

**Comment by wladpaiva** [comment]
There you go. Sounds good to me

**Comment by pontusab** [comment]
Awesome! And then we have this too
![GS2pGMVWQAAGFCk](https://github.com/user-attachments/assets/b4310b20-6349-47d6-a9bc-7243ec472307)

**Comment by pontusab** [comment]
The new time tracker is now done!
