### ISSUE TITLE
Invert Transactions Values in Account Settings

### ISSUE THREAD

**Issue by nspeer12** [midday-ai/midday#141]
Transaction data imported from certain accounts, specifically credit cards, import transactions as positive values. This leads to spending transactions reported as income, and credit card balances being reported as positive account balances, which leads to miscalculations across the application. Likewise, negative transactions from these accounts (ex: refund on a purchase) is reported as spending.

Proposed Solution: Add toggle-switch in the Accounts page to invert values imported from specific accounts. All transactions from that account will be multiplied by -1.

**Comment by pontusab** [comment]
hey! we will have a proper fix for this next week! Would love to have you test this once fixed!

**Comment by pontusab** [comment]
are you connected via teller or plaid?

**Comment by pontusab** [comment]
I have found the issue on both Teller and Plaid, it will be fixed in our Engine V1 PR https://github.com/midday-ai/midday/pull/143 expect it to be released early next week! We will also fix all previous transactions!

**Comment by pontusab** [comment]
Hey @nspeer12, this should now be resolved. 

Please let me know otherwise!
