### ISSUE TITLE
Deleting inbox entries does not remove them from "todo" view

### ISSUE THREAD

**Issue by jakobskrym** [midday-ai/midday#146]
Currently, deleting items in the inbox does not remove them from the to-do view of the inbox. Makes it difficult to achieve "inbox zero" and get that peace of mind.

If you help point me in the right direction for where you want to handle this I can try to open a PR for it.

**Comment by pontusab** [comment]
Hey @jakobskrym, thanks for reporting this! 

It's now fixed and out in production, let me know how it goes!

best
Pontus

**Comment by jakobskrym** [comment]
Works great now! Nice one @pontusab

**Comment by pontusab** [comment]
thank you 🫶
