### ISSUE TITLE
No local development instructions in Midday docs

### ISSUE THREAD

**Issue by Sayantan-s** [midday-ai/midday#162]
There are no instructions or contribution guidelines for local development included in the documentation.

<img width="1433" alt="Screenshot 2024-06-19 at 12 59 38 PM" src="https://github.com/midday-ai/midday/assets/53304368/d68a67d1-d938-45bf-8726-900df6c8acfa">

**Comment by chouglesaud** [comment]
yes i'm also looking to setup locally. but no documentation at the moment.
