### ISSUE TITLE
Typo in system prompt of assistant

### ISSUE THREAD

**Issue by sahildave** [midday-ai/midday#182]
Was taking a look at the assistant code and noticed typos in the system prompt.

File link: https://github.com/midday-ai/midday/blob/main/apps/dashboard/src/actions/ai/chat/index.tsx#L107

**Current state**
`You are a helful asssitant in Midday...`

**Expected state**
`You are a helpful assistant in Midday...`

**Comment by pontusab** [comment]
Thanks! 🥇
