### ISSUE TITLE
Issue with User Invitation

### ISSUE THREAD

**Issue by philipp6690** [midday-ai/midday#185]
The system is designed to forward to /setup route after login if the full_name property on the user is missing.
Invited users get to that page after login instead of the teams/invite/code page where the server accepts their invite.
Not sure If I got that wrong, but in the current process, the invited user is forced to create a new team first and can then accept the invite for the team he/she was invited for.

**Comment by pontusab** [comment]
Oh good catch, I will have a look!

**Comment by rohanprasadofficial** [comment]
@pontusab, can i try this out ?
