### ISSUE TITLE
Asking for the future of the mobile app

### ISSUE THREAD

**Issue by bidah** [midday-ai/midday#216]
Hello there. I was looking at the codebase. It's really cool. Congrats. Bumped into the empty Expo app when browsing. So wanted to ask if there are plans on building it.

**Comment by pontusab** [comment]
Hey! Yes, we are pushing for our V1 in October, after that we will create a mobile app! We thinking about doing a assistant based version! (WIP): https://www.figma.com/proto/AB1bkRqJ1h84lvURBThCxD/App?page-id=66%3A890&node-id=66-1149&starting-point-node-id=66%3A891&t=3uG5c9xXGA1X5eBK-1

**Comment by bidah** [comment]
I like the idea of a subset that focus on the assistant instead of of 1 to 1 parity. looks great.
