### ISSUE TITLE
Cancel button in Create Team modal behaves incorrectly

### ISSUE THREAD

**Issue by BharathxD** [midday-ai/midday#225]
[![Bug Video](https://github.com/user-attachments/assets/9ebede77-ca8a-49cf-a216-bb389bb084f2)](https://github.com/user-attachments/assets/9ebede77-ca8a-49cf-a216-bb389bb084f2)

Hey there! I noticed a bug with the Cancel button in the Create Team modal on the Teams page (https://app.midday.ai/account/teams). It's acting up in two ways:

1. If the modal's empty and you hit Cancel, it shows a validation error instead of just closing.
2. If you've typed something and hit Cancel, it actually submits the form instead of, you know, cancelling.

## Steps to Reproduce
1. Head over to https://app.midday.ai/account/teams
2. Click "Create Team" to pop open the modal
3. Try these two scenarios:
   a. Without typing anything, click Cancel
   b. Type some team name, then click Cancel

## Expected Behavior
Ideally, when you click Cancel:
- The modal should just close
- Any text you typed should be discarded
- You shouldn't see any validation errors
- And it definitely shouldn't create a team

## Actual Behavior
1. Empty modal + Cancel click:
   - You get a validation error
   - Modal stays open
2. Filled modal + Cancel click:
   - The form submits
   - A team gets created (oops!)

**Comment by pontusab** [comment]
Thank you so much for this issue and fix!

**Comment by BharathxD** [comment]
Hello @pontusab! I took another look at it, and it seems the cancel button isn't working anymore. I've submitted a PR to fix that problem. But, I couldn't test it myself as I haven't set up this repo in my local environment yet :_)

Keep up the awesome work, by the way!
