### ISSUE TITLE
Application error: a client-side exception has occurred (see the browser console for more information). getting this error sometime while clicking on pricing section of main website

### ISSUE THREAD

**Issue by HakaishinShwet** [midday-ai/midday#236]
```
ChunkLoadError: Loading chunk 5898 failed.
(error: https://midday.ai/_next/static/chunks/80507811-bc212ff1571a1a39.js)
    NextJS 21
[286-2fac78fc5f639562.js:1:3970](https://midday.ai/_next/static/chunks/286-2fac78fc5f639562.js)
Uncaught Error: Minified React error #423; visit https://react.dev/errors/423 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    NextJS 31
```

this the console error of my firefox. I get this error sometime and sometime it opens after sometime if left for some mins idk quite strange behavior i observed so reporting here just in case if there are nay bugs in website so it can be fixed . It does mentioned client side error so maybe its not properly compatible with firefox? or maybe something else anyways you can close if there are no changes need to be made in website :-))

**Comment by pontusab** [comment]
Thanks, it's something with spline, I will have a look!

**Comment by pontusab** [comment]
Should be fixed now, thanks!
