### ISSUE TITLE
3D spiral overlaps with text beside it

### ISSUE THREAD

**Issue by GhoulKingR** [midday-ai/midday#242]
I noticed that between the screen sizes 768px and 1279px this happens:

![Screenshot 2024-09-02 at 14 21 40](https://github.com/user-attachments/assets/43afccf2-6961-4377-a63f-f2e5952e764a)

I don't know if that's the intended behavior, but I just wanted to point it out.

**Comment by pontusab** [comment]
Thanks, will fix that!
