### ISSUE TITLE
Application error on the root page of the application while navigating to another route.

### ISSUE THREAD

**Issue by IftequarIffu** [midday-ai/midday#26]
Hello Team!

### Description
There's an application error I faced while browsing through the application.

### Steps to reproduce
- Go to the root page of the application i.e., https://midday.ai/
- Hover on the **Developers** section of the navigation bar on top and click on **Apps and Integrations** section.
- Apps and Integrations section can be opened in the new tab.
- Stay on the same tab for some time(15 secs).
- Now, come back to the main root tab. 
- You will see the application error.

### Cause of the error

It looks like there's an object or variable named "animate" which is null at the moment of browsing, which is causing the application error. This can be found by checking the browser console.

**I would like to work on this issue and I request you to assign me this bug.**

Video Link: https://github.com/midday-ai/midday/assets/47710788/acf5b4e6-ecef-42b6-801e-0643c986e0f4

**Comment by pontusab** [comment]
Please do! the code is in here: https://github.com/midday-ai/midday/blob/main/apps/website/src/components/glowing-stars.tsx

**Comment by Ankitmohanty2** [comment]
will u assign me this issue ??
i would love to contribute.

**Comment by pontusab** [comment]
@Ankitmohanty2 Thanks for showing interest in fixing this, while @IftequarIffu created the issue and expressed wanting to help I assigned IftequarIffu to this.

**Comment by pontusab** [comment]
After we switched to PPR, I can't really trigger this again. I will close this and open if there still are issues, thanks!

**Comment by IftequarIffu** [comment]
Hey! I wasn't able to reproduce the issue either. It looks like the issue is fixed. Thanks!
