### ISSUE TITLE
Manually add accounts and update balances

### ISSUE THREAD

**Issue by jakobskrym** [midday-ai/midday#261]
We have the majority of our funding in a separate bank account without integration through GoCardLess, I believe Tink has it though. 

Would be great to be able to set up an account with manual updates to the balance every now and then to reflect this account 👍

Especially if you're going to venture more in the direction of runway analysis etc, which is going to be quite useless unless you can get a full view of the finances.

**Comment by pontusab** [comment]
Great idea! the only thing we are missing is to update the balance from settings -> accounts

also let me know what bank it is and i will ask go to add it!

**Comment by jakobskrym** [comment]
> Great idea! the only thing we are missing is to update the balance from settings -> accounts
> 
> also let me know what bank it is and i will ask go to add it!

Avanza, they have a pretty decent interest deal 💰

**Comment by pontusab** [comment]
This is now supported!
<img width="861" alt="Screenshot 2024-10-05 at 09 13 30" src="https://github.com/user-attachments/assets/27caa9dd-829d-4ec2-827f-774a0b3e38c4">

**Comment by jakobskrym** [comment]
> This is now supported! <img alt="Screenshot 2024-10-05 at 09 13 30" width="861" src="https://private-user-images.githubusercontent.com/655158/373853689-27caa9dd-829d-4ec2-827f-774a0b3e38c4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyODgxNDYsIm5iZiI6MTcyODI4Nzg0NiwicGF0aCI6Ii82NTUxNTgvMzczODUzNjg5LTI3Y2FhOWRkLTgyOWQtNGVjMi04MjdmLTc3NGEwYjNlMzhjNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwN1QwNzU3MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNmVkMzgwMGQ5YjlhMGYyYTY3ZWVkMWZhZWNkNmNhY2U2ZGRmMjk4Zjc2NWMzODAzY2I5MTFlYzk0N2Y2MDMyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.IXz6lB-W5OO9lFl-SNzVudVx5YxxCO1xrgXhduOVLo4">

There's still some friction because the creation of a new account is built around connecting to an existing bank and then importing transactions through a file. So in my case, I don't really have either of those, and instead want to manually update the balance over time, but I can't really get there now since I can't "start blank".

**Comment by pontusab** [comment]
Sorry if i'm being stupid, but you can create a manual account without a bank connection.
You can then update your balance in Settings -> Accounts -> Edit bank account

Let me know if I misunderstood this!

**Comment by jakobskrym** [comment]
<img width="1069" alt="Screenshot 2024-10-08 at 10 26 50" src="https://github.com/user-attachments/assets/fca6e893-d068-451b-8fce-a46b3abbe2dd">

Thing is, I can't even get any transactions csv from the account, and the current manual account creation is based around uploading a CSV or screenshot of transactions, there is no option to just start with a manually entered balance. 

I suggest adding a button under the drop zone to "create without transactions", which maybe asks the user to manually enter a balance or similar.
