### ISSUE TITLE
Error: login#error=server_error&error_code=500&error_description=Database+error+saving+new+user

### ISSUE THREAD

**Issue by pmualaba** [midday-ai/midday#268]
![image](https://github.com/user-attachments/assets/25203494-cf43-4c17-811c-861a96bb3a36)

**Comment by pmualaba** [comment]
In the DB logs :
172.21.0.6 2024-10-03 12:52:30.449 UTC [356] supabase_auth_admin@postgres ERROR:  null value in column "url" of relation "http_request_queue" violates not-null constraint

**Comment by pmualaba** [comment]
Same issue with OTP login:
![image](https://github.com/user-attachments/assets/2c43cde8-bf4b-4570-a8c0-91c879111120)

**Comment by pmualaba** [comment]
not sure if it could be related to this? : https://github.com/orgs/supabase/discussions/21247

**Comment by pontusab** [comment]
Hey, documentation will come after our v1 release, until then we don't have the bandwidth to fix this. V1 is planned to be done in December!
