### ISSUE TITLE
add functionality: Export transactions to CSV file

### ISSUE THREAD

**Issue by OleksandrKucherenko** [midday-ai/midday#269]
Will be great to have ability to export selected/filtered transactions to the CSV file or Google Sheet from transaction screen.

Use cases:
- use google sheet for processing the transactions data
- work with openAI by providing a CSV file for analysis

Filters:
- by dates period (1 week, 1 month, 1 quart, 6 months, 1 year, fiscal year)
- by category
- by selected transactions only

p.s. think about JSON too, it can work for openAI as a source of structured data

p.p.s. it can be "download of the file" created in memory, or it can be a shared link to the data that can be used for fetching data  from google sheet formula (with link expiration time)

**Comment by pontusab** [comment]
This is already supported!
<img width="1591" alt="Screenshot 2024-10-03 at 14 01 21" src="https://github.com/user-attachments/assets/7a4808c1-8b0d-4686-ae20-2920701ddc1f">
<img width="863" alt="Screenshot 2024-10-03 at 14 01 30" src="https://github.com/user-attachments/assets/ca15a3cf-1b4c-49f9-808d-195631e9987b">
<img width="1590" alt="Screenshot 2024-10-03 at 14 00 45" src="https://github.com/user-attachments/assets/afb3af11-24ba-4816-b0c5-b396c5c51440">

**Comment by OleksandrKucherenko** [comment]
ah-a, I look in the wrong place... under Actions button
