### ISSUE TITLE
feature request: integration with Marqueta (and Stripe)

### ISSUE THREAD

**Issue by OleksandrKucherenko** [midday-ai/midday#270]
Overview:
- finance-as-a-service providers [Marqueta](https://www.marqeta.com/) (and [Stripe](https://stripe.com/en-se))
- they can be used for creating Virtual Plastic cards with limits and budgeting rules

Possible UI: https://demo.mercury.com/cards

| P1 | P2 |
| -- | -- | 
| <img width="414" alt="image" src="https://github.com/user-attachments/assets/10ad0b5e-7452-45eb-aac1-a9f3041eb86b"> | <img width="413" alt="image" src="https://github.com/user-attachments/assets/862d4856-43f3-4ab1-8381-cab1648e97fd"> |
| <img width="456" alt="image" src="https://github.com/user-attachments/assets/7ade7430-27b1-424f-8bc7-cf8b7d251977"> | <img width="459" alt="image" src="https://github.com/user-attachments/assets/aa210281-7978-45e6-ab75-d36085f4bbb2"> |

**Comment by OleksandrKucherenko** [comment]
You can also take a look on [Mastercard API](https://developer.mastercard.com/products)

**Comment by pontusab** [comment]
Yes this is something we will explore once we have reached a certain level of paying customers, Stripe costs a lot upfront and so do Adyen (we have had great meetings with Adyen regarding this) but we will keep everyone updated regarding this decision moving forward!
