### ISSUE TITLE
[feature] Holidays in calendar

### ISSUE THREAD

**Issue by OleksandrKucherenko** [midday-ai/midday#280]
Overview
- It would be great to highlight holidays in the calendar.

Best solutions:
- Users can specify multiple links as sources of holiday information and, with the help of AI and a web-crawler, extract a CSV with holidays.

links examples:
- https://www.riksbank.se/en-gb/press-and-published/calendar/holidays-2024/
- https://www.timeanddate.com/holidays/sweden/
- https://publicholidays.se/school-holidays/stockholm/
- https://www.kth.se/blogs/studentblog/2021/02/annual-traditions-in-sweden/
- https://www.onfoodietrail.com/most-popular-swedish-fika-pastries/
- https://www.calendarr.com/united-states/observances-2022/
- https://www.routesnorth.com/things-to-do-in-sweden/a-quick-guide-to-swedish-holidays-and-traditions/
- https://www.thereisadayforthat.com/countries/sweden/2022

![image](https://github.com/user-attachments/assets/9f1db582-cc58-4427-be1a-778050c5caa9)

**Comment by pontusab** [comment]
Thanks for the suggestions, I think it's a bit out of scope for the time tracker, while it's a calendar it's not related to a regular schedule. If we get this feedback more I will re-evaluate!
