### ISSUE TITLE
Connection error when interacting with Assistant

### ISSUE THREAD

**Issue by anteriovieira** [midday-ai/midday#281]
When asking a complex question to the Midday AI assistant, the application encountered a connection error. The error message "Uncaught (in promise) Error: Connection closed" appeared in the browser console, suggesting that the connection was terminated unexpectedly.

> This issue may be caused by the AI generating a response that exceeds the size limit for the connection, resulting in a premature closure. The error occurred during an interaction with the AI assistant, potentially disrupting the user experience.

Steps to reproduce:
1. Open the Midday AI application
2. Ask a complex question that might require a lengthy response

The application displays a client-side exception, and the browser console shows a connection closed error, preventing the AI from completing its response.

<img width="1435" alt="image" src="https://github.com/user-attachments/assets/5ea397b9-891a-4163-9ba8-bb5ca0320312">

**Comment by anteriovieira** [comment]
I think it can be related.

https://github.com/vercel/ai-chatbot/issues/291#issuecomment-2386532815

**Comment by pontusab** [comment]
Thank you, I will have a look!

**Comment by pontusab** [comment]
Should be fixed now!
