### ISSUE TITLE
Incorrect base currency used on Invoices page

### ISSUE THREAD

**Issue by harrybaines** [midday-ai/midday#331]
Really love using this app, you guys have done an amazing job!

Just had a small issue with my base currency - I've set GBP as my base currency, but in the invoices page it shows the invoice in dollars. Maybe it's not referencing the base currency in the invoices page?

**Comment by pontusab** [comment]
Thank you! We use the base currency as default if it's set, but you can change the currency in the invoice template in the settings up to the right!

Let me know if you need any help with that!
