### ISSUE TITLE
Popover of Profile in Theme Section Remains Basic HTML; Dark Theme Visibility Issues

### ISSUE THREAD

**Issue by FindMalek** [midday-ai/midday#34]
Description:
I've noticed a couple of issues in the theme section that I'd like to bring to your attention.

1. **Popover of Profile in Theme Section:** The popover of the profile in the theme section is still basic HTML. I was expecting to see a proper dropdown menu implemented by now. This could enhance the user experience and align more with the overall design of the platform.

2. **Dark Theme Visibility:** In the dark theme, the content within the popover is not visible. This appears to be a CSS issue where the text color might not be adjusting properly to the dark background. This lack of visibility can make it difficult for users who prefer the dark theme to navigate and use the popover effectively.

I've attached a screenshot for reference. Please let me know if you need any more information.
![image](https://github.com/midday-ai/midday/assets/74460583/3bad60a5-f834-4cb7-a8bd-7e56813e702b)
![image](https://github.com/midday-ai/midday/assets/74460583/64490851-ed14-473f-9333-65916dd90444)

Looking forward to seeing these issues addressed in future updates. Thank you for your time and consideration.

**Comment by FindMalek** [comment]
A small fix!
Even tho I feel if you guys used Shadcn select would be better!

`switch-theme.tsx
````
"use client";

import { useTheme } from "next-themes";
import { Icons } from "@component/icons/Lucide";

type Theme = "dark" | "system" | "light";

type Props = {
  currentTheme?: Theme;
};

const ThemeIcon = ({ currentTheme }: Props) => {
  switch (currentTheme) {
    case "dark":
      return <Icons.moon size={12} />;
    case "system":
      return <Icons.monitor size={12} />;
    default:
      return <Icons.sun size={12} />;
  }
};

export function ThemeSwitch() {
  const { theme, setTheme, themes } = useTheme();

  return (
    <div className="flex items-center relative">
      <select
        className="text-xs border rounded-md appearance-none pl-6 pr-6 py-1.5 dark:bg-black outline-none capitalize w-full"
        defaultValue={theme}
        onChange={(event) => setTheme(event.target.value)}
      >
        {themes.map((theme) => (
          <option key={theme} value={theme}>
            {theme}
          </option>
        ))}
      </select>

      <div className="absolute left-2 pointer-events-none">
        <ThemeIcon currentTheme={theme as Theme} />
      </div>

      <div className="absolute right-2">
        <Icons.chevronsUpDown size={12} />
      </div>
    </div>
  );
}
```
`

**Comment by pontusab** [comment]
Thank you! I used shadcn as you mentioned instead!
