### ISSUE TITLE
Expose code for MFA

### ISSUE THREAD

**Issue by wladpaiva** [midday-ai/midday#41]
If the app fails to load the qrcode for some reason, there's no way currently to confirm the 2FA. Ideally the code for creating it manually should be visible somewhere

**Comment by pontusab** [comment]
Perfect, thank you!

I will expose the `secret` from https://supabase.com/docs/reference/javascript/auth-mfa-enroll

**Comment by pontusab** [comment]
<img width="552" alt="Screenshot 2024-03-25 at 07 59 27" src="https://github.com/midday-ai/midday/assets/655158/0e283c7e-86ce-402e-b8fb-d040e6879d03">

Fixed!
