### ISSUE TITLE
Not found page is not fetching data

### ISSUE THREAD

**Issue by FindMalek** [midday-ai/midday#42]
Hey once again!
I keep submitting issues to deliver the best product for the community I love you work!

The not found page would simply keep saying 'Data failed..." because the `NotFoundTerminal` is not an asynchronous component that fetches actual data

You need to do something like this! to show the Suspense Status Widget

```
export async function NotFoundTerminal() {
  const data = await dataFetcher();
  ....
}
```

I could make a PR to fix this! Also I'm open to work with you on midday, I truly love the idea

![image](https://github.com/midday-ai/midday/assets/74460583/adf47058-3f81-49a1-a2c8-5b39aa0fc13a)

**Comment by pontusab** [comment]
Thanks! The 404 Data not found... is just for show, and not actually doing anything.
