### ISSUE TITLE
Dockerfile 

### ISSUE THREAD

**Issue by Pratham271** [midday-ai/midday#61]
We could add a docker and a docker-compose file to make it easy for the devs to setup the project.

**Comment by Pratham271** [comment]
If you want it I'll be happy to contribute.

**Comment by bytebisha** [comment]
Yes would love to contribute to midday.

**Comment by pontusab** [comment]
Hey, thanks for wanting to help as you already noticed we are not quite there yet. We will add a dockerfile + get started documentation next week but feel free to give us feedback once commited!
