### ISSUE TITLE
Supabase SQL schema 

### ISSUE THREAD

**Issue by WeiY** [midday-ai/midday#85]
When I tried to self host the midday dashboard, there is an error with getUser (cannot find the relationship between user id and team id). Maybe because I don’t create any table in Supabase. Right now I only found the generated typescript types and there is no SQL schema. Is there anyway to create tables in Supabase? Thanks!

**Comment by pontusab** [comment]
Yes, we are using supabase replicas and there is currently an issue generating the SQL schema, we will add it asap once fixed!

**Comment by WeiY** [comment]
Thanks very much for reply! And if you have a simple document about how to setup the Supabase (like replicas) for dashboard running on self-host, that will be perfect.

**Comment by atresnjo** [comment]
I've thought about creating it with the use of ChatGPT (convert TS types to CREATE statements), got close but cannot figure out the views because I have no idea where decrypted_name is taken from, any help? 👍

**Comment by atresnjo** [comment]
I got a lot working, can't seem to figure out the transaction view :D 

![image](https://github.com/midday-ai/midday/assets/41112852/aae3cbdb-1dcf-4302-8e6c-e0a9099f5078)

![image](https://github.com/midday-ai/midday/assets/41112852/02f10ebc-a504-40f5-8cdc-0e1b23a41479)

got plaid and most of the stuff connected too, i guess my views are a bit wrong 😆

**Comment by pontusab** [comment]
Hey, im in contact with supabase regarding generate the schema when you have 1. replicas 2. encryption on row level (that you notice here) because we use Vault to store keys and those are unique to every project (ofc)

I'll let you know when we have a plan here!

**Comment by azlekov** [comment]
Can someone put some notes or steps for self-hosting this? I want to play around with it.

Many thanks!

**Comment by cathalm1** [comment]
@pontusab any updates on when the sql schema will be released?

**Comment by pontusab** [comment]
We now have the schema in the repo 👍 https://github.com/midday-ai/midday/tree/main/packages/supabase/migrations

Documentation will be ready after our ProductHunt release in 2 weeks!
